#!/bin/bash
#
# quick starter
#   1. put this into ~/bin/
#   2. decide to add -q or not aka.( quick mode will skip intro step )
#   3. check your $PATH
#  
export MINISHIFT_USERNAME="RHNUSER"
export MINISHIFT_PASSWORD="RHNPASS"

# lab.sh requireds bash 4
OS=$(uname -s)

case $OS in 
	Darwin) SHELL="/usr/local/bin/bash";;
  Linux) SHELL="/bin/bash";;
esac

$SHELL $HOME/git/cdk-labs/lab.sh "$@"
