apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv01
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /exports/miq-pv01
    server: <your-nfs-host-here>
  persistentVolumeReclaimPolicy: Retain
